---
# tasks file for panxatony.nginx

- name: Install Nginx
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - nginx
    - httpd-tools
  become: yes
  become_user: root
  tags:
    - nginx

- name: make sure nginx is running
  service: name=nginx state=started enabled=yes
  become: yes
  become_user: root
  tags:
    - nginx

- name: start firewalld service
  service: name=firewalld state=started enabled=yes
  become: yes
  become_user: root
  tags:
    - nginx

- name: enable seboolean httpd_can_network_connect
  seboolean: name=httpd_can_network_connect state=on persistent=yes
  when: ansible_selinux.status is defined and ansible_selinux.status == 'enabled'
  become: yes
  become_user: root
  tags:
    - nginx

- name: Make sure basic ports are opened in the firewall
  firewalld: port="{{ item }}" permanent=true state=enabled
  with_items: nginx_firewall_allow_ports
  when: nginx_firewall_allow_ports is defined
  when: nginx_activate_firewall == true
  notify:
    - restart firewalld
  become: yes
  become_user: root
  tags:
    - nginx