---
# handlers file for panxatony.nginx

- name: restart nginx
  service: name=nginx state=restarted
  become: yes
  become_user: root

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  become: yes
  become_user: root